# Site settings
title: Abrams Ventures
email: chris@abrams.ventures
url: http://www.abrams.ventures
description: "Digital Asset Investments"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Abrams Ventures

# Build settings
markdown: kramdown
permalink: pretty
